### PR TITLE
feat get contacts

### PR DESCRIPTION
**Pull request by khairul-alam-licon**
# Description
- Add `getContacts` feature to the mini app message bridge. This should just pass a list of IDs (each ID represents a contact).
- The "Contacts" setting was already implemented in the Demo App, so this needs to be hooked into the new `getContacts` feature.
- TODO: Implement `getContacts` in JavaScript bridge.

## Links
- MINI-2295

# Checklist
- [x] I have read the [contributing guidelines](../.github/CONTRIBUTING.md).
- [x] I have completed the [SDK Development Learning Path](../.github/CONTRIBUTING.md#SDK-Development-Learning-Path) (if submitting a feature PR)
- [x] I wrote/updated tests for new/changed code
- [x] I removed all sensitive data before every commit, including API endpoints and keys
- [x] I ran `./gradlew check` without errors

### CODE REVIEW

**Review by corycaywood — APPROVED** [review]
Looks good 👍

**Review by minh-rakuten — APPROVED** [review]
👍

**Comment by minh-rakuten** [comment]
After the merge of this one https://github.com/rakutentech/js-miniapp/pull/82, update bridge submodule is necessary.

**Comment by khairul-alam-licon** [comment]
@minh-rakuten bridge submodule is updated. I think, this PR is ready to merge.

**Review by minh-rakuten — APPROVED** [review]

**Pull request merged**
