### PR TITLE
Expose "version id" in MiniAppManifest

### PR DESCRIPTION
**Pull request by khairul-alam-licon**
# Description
- Add a "version id" field in MiniAppManifest. This should be appended to the manifest data.
- Note: 1: Existing cached mini-app manifest will return `null` for versionId, `MiniAppManifest` which will be newly stored will return the versionId.
- Note: 2: I have tried to remove `CachedManifest` because `MiniAppManifest` is going to have the version id from now on, but it seems a breaking change for the host app which has been applied the previous implementation already. But, there is a chance to do that when addressing MINI-2945.

## Links
- MINI-2935

# Checklist
- [x] I have read the [contributing guidelines](../.github/CONTRIBUTING.md).
- [x] I have completed the [SDK Development Learning Path](../.github/CONTRIBUTING.md#SDK-Development-Learning-Path) (if submitting a feature PR)
- [x] I wrote/updated tests for new/changed code
- [x] I removed all sensitive data before every commit, including API endpoints and keys
- [x] I ran `./gradlew check` without errors

### CODE REVIEW

**Review by minh-rakuten — APPROVED** [review]
LGTM.

Is there anything we can do to improve test coverage?

**Comment by khairul-alam-licon** [comment]
> Is there anything we can do to improve test coverage?

Yeah, probably we can add more testcase for the `versionId` if possible.

**Comment by minh-rakuten** [comment]
> Yeah, probably we can add more testcase for the `versionId` if possible.

@khairul-alam-licon actually, I mean you can add more test cases based on the missing coverage report.

**Review by corycaywood — APPROVED** [review]
LGTM 👍

**Pull request merged**
