### PR TITLE
[MINI-5831] Update settings UI to be similar as on ios

### PR DESCRIPTION
**Pull request by shohiebsense**
# Description
1. Move the Query Parameters and Deeplink to General Settings Page.
2. Add/Edit Contact from Dialog to Activity (Page)

## Links
[MINI-5831](https://jira.rakuten-it.com/jira/browse/MINI-5831)

## Screenshots
https://rak.box.com/s/ypwdrrt9iqrcnh3tyb1xuif4f55ngvv3
https://rak.box.com/s/gpetmns7o8nuje7ynazdk9lep60b5y5j
https://rak.box.com/s/0o2i5j6pr1b2q481d2qdb43jwgsysos9

## Video
https://rak.box.com/s/358o1qfxohzcfxnxliter53gsa1u28uo

# Checklist
- [x] I have read the [contributing guidelines](https://github.com/rakutentech/android-miniapp/blob/master/.github/CONTRIBUTING.md).
- [x] I have completed the [SDK Development Learning Path](https://github.com/rakutentech/android-miniapp/blob/master/.github/CONTRIBUTING.md#sdk-development-learning-path) (if submitting a feature PR)
- [ ] I wrote/updated tests for new/changed code
- [x] I removed all sensitive data before every commit, including API endpoints and keys
- [x] I ran `./gradlew check` without errors

### CODE REVIEW

**Review by munir-rakuten — APPROVED** [review]
Looks good to me, i think we can add the changes in `CHANGELOG`.

**Review by rleojoseph — APPROVED** [review]
Looks good to me :+1:

**Review by khairul-alam-licon — CHANGES_REQUESTED** [review]
basically, looks good, 
There is an issue while pressing remove (-) button as we discussed. 
Sorry for requested changes 🙇‍♂️

**Review by khairul-alam-licon — APPROVED** [review]
Working fine 👍 
LGTM

**Comment by shohiebsense** [comment]
Thanks a lot for the catch

**Pull request merged**
