### PR TITLE
[MINI-5613] Set Default values settings

### PR DESCRIPTION
**Pull request by munir-rakuten**
# Description
Make `Production` mode default and set default values for

- profile name
- profile pic
- points

## Links
MINI-5613

# Checklist
- [x] I have read the [contributing guidelines](https://github.com/rakutentech/android-miniapp/blob/master/.github/CONTRIBUTING.md).
- [x] I have completed the [SDK Development Learning Path](https://github.com/rakutentech/android-miniapp/blob/master/.github/CONTRIBUTING.md#sdk-development-learning-path) (if submitting a feature PR)
- [x] I removed all sensitive data before every commit, including API endpoints and keys
- [x] I ran `./gradlew check` without errors

### CODE REVIEW

**Review by laubengaier — COMMENTED** [review]
good job, lgtm overall.
Just one question are the contacts also set as default values? I can't see changes related to that otherwise I'll approve.

**Comment by munir-rakuten** [comment]
> good job, lgtm overall.
> Just one question are the contacts also set as default values? I can't see changes related to that otherwise I'll approve.

yeah, i missed that one, added now.

**Review by laubengaier — APPROVED** [review]
lgtm!

**Comment by shohiebsense** [comment]
lgtm, I prefer the names[] are separated from SettingsFragment.kt  to be fair... @munir-rakuten

**Comment by munir-rakuten** [comment]
> lgtm, I prefer the names[] are separated from SettingsFragment.kt to be fair... @munir-rakuten

updated, please check.

**Review by shohiebsense — APPROVED** [review]
Let's gooooo

**Pull request merged**
