### PR TITLE
Refactor/ios parity

### PR DESCRIPTION
**Pull request by minh-rakuten**
# Description
Keep the parity of downloading mini app flow between android & ios.

1/ Loading miniapp from MiniAppInfo -> 2/ Call api get Manifest files -> 3/ Load from local or Download from server

Change in android:
Removing unnecessary `isLatestVersion` function because the server already handled this.
Only catch and throw an exception from the server response. This also improves the loading speed when getting miniapp.

# Checklist
- [x] I have read the [contributing guidelines](../CONTRIBUTING.md).
- [x] I wrote/updated tests for new/changed code
- [x] I removed all sensitive data before every commit, including API endpoints and keys
- [x] I ran `./gradlew check` without errors

### CODE REVIEW

**Comment by ts-nitish-a-jain** [comment]
@minh-rakuten Could you please link the "back end update discussion" where it has been updated?

**Comment by minh-rakuten** [comment]
> @minh-rakuten Could you please link the "back end update discussion" where it has been updated?

@ts-nitish-a-jain There is no comment discussion from backend but it's good to implement the same flow as iOS.
I also tested with api and the backend already solved this case.

**Comment by minh-rakuten** [comment]
> Let's hook up the discussion or API spec change before we commit this.

Okay. @ts-nitish-a-jain Please take your time on getting confirmation from BE.

**Comment by minh-rakuten** [comment]
iOS will update which is following android. Both platforms accept slower loading time due to the agreement on design flow 😑

**Pull request closed without merging**
