### PR TITLE
Fix issues in user details settings

### PR DESCRIPTION
**Pull request by khairul-alam-licon**
# Description
Two issues have been fixed by this PR on user details settings screen in sample app.
- `No contact available!` text was not showing because of a xml shape, it's fixed in this PR
- Photo can be picked from gallery by tapping on the photo
- Shrink margin at build info to look good

## Links
- MINI-955

# Checklist
- [x] I have read the [contributing guidelines](../CONTRIBUTING.md).
- [ ] I wrote/updated tests for new/changed code
- [x] I removed all sensitive data before every commit, including API endpoints and keys
- [x] I ran `./gradlew check` without errors

### CODE REVIEW

**Review by corycaywood — APPROVED** [review]
👍

**Comment by khairul-alam-licon** [comment]
Sorry, added a new commit: https://github.com/rakutentech/android-miniapp/pull/156/commits/6d1e4b5ecc32a1660c515535e1c9291fc0b4fbd1 as a small UI improvement.

**Review by minh-rakuten — APPROVED** [review]
Android UI is not as good as iOS. I don't know how to improve it either.

**Comment by khairul-alam-licon** [comment]
Android app need a designer :D

**Comment by khairul-alam-licon** [comment]
Android app needs a designer :D

**Pull request merged**
