### PR TITLE
MINI-3325: demo app: enhancements for Contact ID, name and email inputs

### PR DESCRIPTION
**Pull request by khairul-alam-licon**
# Description
This PR will add few enhancements for Contact ID, name and email adding in demo app e.g. 
- contact id, name and email inputs should not be empty
- refactoring random contacts generation with iOS-like values
- displaying a default random contact while adding a new contact

P/S: There is already an email validation, so it has been skipped.

## Links
- MINI-3325

# Checklist
- [x] I have read the [contributing guidelines](../.github/CONTRIBUTING.md).
- [x] I have completed the [SDK Development Learning Path](../.github/CONTRIBUTING.md#SDK-Development-Learning-Path) (if submitting a feature PR)
- [ ] I wrote/updated tests for new/changed code
- [X] I removed all sensitive data before every commit, including API endpoints and keys
- [x] I ran `./gradlew check` without errors

### CODE REVIEW

**Review by corycaywood — APPROVED** [review]
LGTM 👍

**Review by munir-rakuten — COMMENTED** [review]
Looks good to me!! 👍

**Comment by khairul-alam-licon** [comment]
@munir-rakuten I have synced with latest changes from `master` branch. Please review once again, Thank you!

**Review by munir-rakuten — APPROVED** [review]
LGTM! 👍

**Pull request merged**
