### PR TITLE
ci: Setup Demo App publishing from feature branches

### PR DESCRIPTION
**Pull request by corycaywood**
# Description
Publishes to the "Feature" group on App Center for branches matching `feature/*`.

# Checklist
- [x] I have read the [contributing guidelines](../.github/CONTRIBUTING.md).
- [x] I have completed the [SDK Development Learning Path](../.github/CONTRIBUTING.md#SDK-Development-Learning-Path) (if submitting a feature PR)
- [ ] I wrote/updated tests for new/changed code
- [x] I removed all sensitive data before every commit, including API endpoints and keys
- [x] I ran `./gradlew check` without errors

### CODE REVIEW

**Review by Climbatize — APPROVED** [review]
a nice improvement to our workflow

**Review by khairul-alam-licon — APPROVED** [review]
Looks good 👍

**Review by minh-rakuten — APPROVED** [review]
👍 👍 
Not related but let's do a jump version for staging build in this PR. It is displayed as 2.8.0 for now :(

**Comment by corycaywood** [comment]
> 👍 👍
> Not related but let's do a jump version for staging build in this PR. It is displayed as 2.8.0 for now :(

Okay, good idea - I merged `candidate` into my branch and it seems to be working now.

I think this happened because we need to use the `Create a merge commit` button when merging the `candidate` branch to `master` after a release (instead of using `Squash and merge`).

**Pull request merged**
