### PR TITLE
Update changelog for 3.7.0 

### PR DESCRIPTION
**Pull request by khairul-alam-licon**
# Description
Update changelog for 3.7.0

# Checklist
- [x] I have read the [contributing guidelines](../.github/CONTRIBUTING.md).
- [x] I have completed the [SDK Development Learning Path](../.github/CONTRIBUTING.md#SDK-Development-Learning-Path) (if submitting a feature PR)
- [x] I wrote/updated tests for new/changed code
- [x] I removed all sensitive data before every commit, including API endpoints and keys
- [x] I ran `./gradlew check` without errors

### CODE REVIEW

**Review by Climbatize — APPROVED** [review]
LGTM

**Review by munir-rakuten — COMMENTED** [review]
I think rat events in demo app is missing , so we can add in sample app
` **Feature:** Added additional rat events to track the host app by adding custom views.`

**Review by corycaywood — APPROVED** [review]
Looks good 👍

**Review by munir-rakuten — APPROVED** [review]
LGTM 👍

**Pull request merged**
